export enum AnchorPoint {
    ANCHOR_H_MASK = 0x00f0,
    ANCHOR_TOP    = 0x0010,
    ANCHOR_BOTTOM = 0x0020,
    ANCHOR_V_MASK = 0x000f,
    ANCHOR_LEFT   = 0x0001,
    ANCHOR_RIGHT  = 0x0002,
    ANCHOR_MIDDLE = 0x0000,

    ANCHOR_TOP_LEFT = ANCHOR_TOP | ANCHOR_LEFT,
    ANCHOR_TOP_RIGHT = ANCHOR_TOP | ANCHOR_RIGHT,
    ANCHOR_BOTTOM_LEFT = ANCHOR_BOTTOM | ANCHOR_LEFT,
    ANCHOR_BOTTOM_RIGHT = ANCHOR_BOTTOM | ANCHOR_RIGHT
}

